#include "GaudiKernel/LoadFactoryEntries.h"

LOAD_FACTORY_ENTRIES( Sigma0PionPi0 )
LOAD_FACTORY_ENTRIES( Sigma0PionEta )
LOAD_FACTORY_ENTRIES( Sigma0PipPipPim )
LOAD_FACTORY_ENTRIES( Sigma0Pip )
LOAD_FACTORY_ENTRIES( SigmapPi0Pi0 )

